name: CI

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: git remote add gitlab https://gitlab.com/wcyat/wcyat.gitlab.io.git
      - run: git pull gitlab master && git push origin master
